language: node_js
node_js:
  - node
  - lts/*
before_script:
  - npm run format
  - npm run build
  - ./bin/start_serve.sh
script:
  - npm test
  - ./bin/check_git_clean.sh
after_script:
  - ./bin/stop_serve.sh
deploy:
  skip_cleanup: true
  provider: npm
  email: c.skeppstedt@gmail.com
  api_key:
    secure: C5cBS1Qblp87NnHaAxWwVqGaUMo2afPkg5YUymQFGT8ILtzbrLjD77TJW2aG2CmSXbUx+it73nLLtBfqv5OemTrNd165ez1j5V4hgikgPOlK2rvne/IebMdpFVeyh4C6ippgGkek9AUPSIvlFwgAWi1TtL369pS8ozJl3MLqFJ0EbEC0j660S5e8Zu4TUivjYRK5W1C3aSRw7OlwzQdie8vuKVvKpKtgiM0tyfAaM3UG+d839gXtis2aI+pCeGioH6Db0RN3T4R14f144j86X2R6zEjhZeLBh6d2WUjtQeEyalCPiBiwUJDUvmJfET/IYmL4f8eqCM/8pmXAx5rduqECXLEF76XWCDekj/3itPg8VqkUAs0Unk+iHCSOQcaw4D580umkcS3GzSwKG63U+zvjAIdPfb0HnVXr2/f5K8dik1xjp2C1L8+P+Wwi1xcMf1LvGI2/6z0I/EZJiSIljE8WrZj/iRnlSfcl8we4eh8v62UnKTB/PDRmitZ9jEfp9+gCrZSDK+sBxnlYbh2pKywEGXs+uAoXecWICOWxiNZNc5VKnOTgTqSm1+pkehisXH4VfQ9uMYxa/TVirILUzCk33HB/cf57AmGKZBj4b4xbhrxj7ODAPaIO005HmKWeyoQ4F1ko0adPtPrJAZVZzdy6BPF9tzwi8NchDSdpchg=
  on:
    tags: true
    repo: cskeppstedt/rx-singleton-lock
